env:
  AWS_DEFAULT_REGION: ap-southeast-2

steps:
  - command: echo "Hello World"
    label: ":aws: Doc Site - Deploy Infra - Dev"
    env:
      ENVIRONMENT: dev
    agents:
      queue: pactflow-dev
